# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- master1

pool:
  vmImage: ubuntu-latest

stages:
- stage : Deploy
  jobs:
  - job:
    displayName: Deploy
    steps:    
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
        
    - task: CopyFiles@2
      inputs:
        contents: '/home/vsts/work/1/s/target/*.jar'
        targetFolder: $(Build.ArtifactStagingDirectory)/splinecustomhttpdispatcher.jar
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: MyBuildOutputs
        
    - task: nexusArtifactUpload@0
      inputs:
        serverEndpoint: 'edc-nx2plus-p-sc'
        groupId: 'org.abnamro.dmp.mdc'
        artifactId: 'splinecustomhttpdispatcher'
        repositoryId: ots-releases
        artifactVersion: '1.0.0'
        packaging: 'jar'
        fileName: '$(Build.ArtifactStagingDirectory)/splinecustomhttpdispatcher.jar'
